FormKey: 00D51D:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12341
EditorID: MantellaSettingsTerminal
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: Choose menu
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Main Settings
  Type: SubmenuTerminal
  ItemId: 1
  Submenu: 00D519:Mantella.esp
- ItemText:
    TargetLanguage: English
    Value: Radiant Settings
  Type: SubmenuTerminal
  ItemId: 2
  Submenu: 015DBF:Mantella.esp
MajorFlags:
- 0x10
- 0x2000
